name: practice-job
on: 
  push:
  workflow_dispatch:

env: 
  project: practice

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11 , 3.12]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: python setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}

      - name: cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: my-cache
        
   
  
