name: Docker Project
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Repository file get
        uses: actions/checkout@v4
      - name: build Dockerfile
        run: docker build -t myapp .
      - name: start container
        run: docker run myapp
    
